### ISSUE TITLE
Not working with Abnormals Core

### ISSUE THREAD

**Issue by Snownee** [tnkmods/JEPB#5]
```
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: class com.minecraftabnormals.abnormals_core.common.loot.modification.LootModificationManager onLootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		2: ASM: class net.mehvahdjukaar.supplementaries.setup.ModSetup onLootLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		3: ASM: class com.blockvader.wtimprovements.IllusionerAmbush onLoottableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		4: ASM: class vectorwing.farmersdelight.setup.CommonEventHandler onLootLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		5: ASM: class dan200.computercraft.shared.CommonHooks lootLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		6: ASM: vazkii.quark.content.tools.module.ColorRunesModule@46578f50 onLootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		7: LOWEST
		8: ASM: class com.minecraftabnormals.abnormals_core.core.registry.LootInjectionRegistry onLootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
java.lang.NullPointerException: Cannot invoke "com.minecraftabnormals.abnormals_core.common.loot.modification.LootModificationManager.getModifiers(net.minecraft.util.ResourceLocation)" because "com.minecraftabnormals.abnormals_core.common.loot.modification.LootModificationManager.INSTANCE" is null
	at com.minecraftabnormals.abnormals_core.common.loot.modification.LootModificationManager.onLootTableLoad(LootModificationManager.java:59)
	at net.minecraftforge.eventbus.ASMEventHandler_37_LootModificationManager_onLootTableLoad_LootTableLoadEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.event.ForgeEventFactory.loadLootTable(ForgeEventFactory.java:666)
	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:891)
	at net.minecraft.loot.LootTableManager.lambda$apply$0(LootTableManager.java:40)
	at java.base/java.util.HashMap.forEach(HashMap.java:1425)
	at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:38)
	at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:16)
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127)
	at com.thenatekirby.jepb.plugin.PiglinBarteringRecipeBuilder.getManager(PiglinBarteringRecipeBuilder.java:79)
	at com.thenatekirby.jepb.plugin.PiglinBarteringRecipeBuilder.getPiglinBarteringRecipes(PiglinBarteringRecipeBuilder.java:41)
	at com.thenatekirby.jepb.plugin.JEPBPlugin.registerRecipes(JEPBPlugin.java:37)
	at mezz.jei.load.PluginLoader.lambda$new$5(PluginLoader.java:117)
	at mezz.jei.load.PluginCaller.callOnPlugins(PluginCaller.java:26)
	at mezz.jei.load.PluginLoader.<init>(PluginLoader.java:117)
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:69)
	at mezz.jei.startup.ClientLifecycleHandler.startJEI(ClientLifecycleHandler.java:147)
	at mezz.jei.startup.ClientLifecycleHandler.setupJEI(ClientLifecycleHandler.java:140)
	at mezz.jei.startup.ClientLifecycleHandler.lambda$new$3(ClientLifecycleHandler.java:106)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
```

**Comment by OrangeBurrito** [comment]
This error also occurs without Just Enough Piglin Bartering installed, it may have something to do with Abnormals Core 3.2.0.

( the shortened log: https://pastebin.com/S2XtHFpJ)

**Comment by nkirby** [comment]
Closing this for now. If we see this again I can take a look, but I'm focusing on getting this to work on 1.18 first.
